version: '3.8'

services:
  keycloak:
    extends:
      file: identity-service/docker-compose.yml
      service: keycloak
 
  service-discovery:
    container_name: service-discovery
    build: service-discovery/service-discovery-app
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    healthcheck:
      test: "curl --fail --silent http://localhost:8081/private/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5

  gateway:
    container_name: gateway
    build: gateway/gateway-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      service-discovery:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8081/eureka/
    healthcheck:
      test: "curl --fail --silent http://localhost:8080/private/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5

  prometheus:
    container_name: prometheus
    build:
      context: observability-tools/prometheus
      args:
        ENVIRONMENT: local
    restart: unless-stopped
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml

# Alert manager is set up to send alert to slack, change the slack channel on alertmanager/config/alertmanager-local.yml and change 'api_url' to enable this
  alertmanager:
    container_name: alertmanager
    build:
      context: observability-tools/alertmanager
      args:
        ENVIRONMENT: local
    restart: unless-stopped
    ports:
      - "9093:9093"
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml

  # default user and password: admin
  grafana:
    container_name: grafana
    build: observability-tools/grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./observability-tools/grafana/provisioning/:/etc/grafana/provisioning/